// Package index maintains recall's SQLite search index: a rebuildable cache
// derived from the vault (the source of truth) and optimized for structured and
// full-text search by LLM agents. Schema migrations are applied by goose; the
// relational CRUD layer is generated by sqlc (package db); full-text search is
// hand-written in search.go.
package index

import (
	"context"
	"database/sql"
	"embed"
	"fmt"

	"recall/internal/index/db"
	"recall/internal/memory"

	"github.com/pressly/goose/v3"
	_ "modernc.org/sqlite"
)

//go:embed migrations/*.sql
var migrationsFS embed.FS

// Index is a handle to the SQLite search index.
type Index struct {
	sql *sql.DB
	q   *db.Queries
}

// Open opens (creating if needed) the SQLite database at dbPath and applies all
// pending migrations.
func Open(dbPath string) (*Index, error) {
	sqlDB, err := sql.Open("sqlite", dbPath)
	if err != nil {
		return nil, fmt.Errorf("index: opening %s: %w", dbPath, err)
	}
	if err := migrateUp(sqlDB); err != nil {
		_ = sqlDB.Close()
		return nil, err
	}
	return &Index{sql: sqlDB, q: db.New(sqlDB)}, nil
}

// Close releases the database handle.
func (ix *Index) Close() error { return ix.sql.Close() }

func migrateUp(sqlDB *sql.DB) error {
	goose.SetBaseFS(migrationsFS)
	goose.SetLogger(goose.NopLogger())
	if err := goose.SetDialect("sqlite3"); err != nil {
		return fmt.Errorf("index: goose dialect: %w", err)
	}
	if err := goose.Up(sqlDB, "migrations"); err != nil {
		return fmt.Errorf("index: applying migrations: %w", err)
	}
	return nil
}

// Upsert indexes a memory: it writes the relational row, replaces the memory's
// tags and links, and refreshes its full-text entry — all atomically. relPath
// is the memory's vault-relative path. The body is stored as stripped raw text.
func (ix *Index) Upsert(ctx context.Context, relPath string, m memory.Memory) error {
	tx, err := ix.sql.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("index: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	qtx := ix.q.WithTx(tx)

	raw := StripMarkdown(m.Body)

	if err := qtx.UpsertMemory(ctx, db.UpsertMemoryParams{
		ID:        m.ID,
		Path:      relPath,
		Title:     m.Title,
		Domain:    m.Domain,
		Project:   m.Project,
		Source:    m.Source,
		Lifecycle: string(m.Lifecycle),
		ExpiresOn: m.ExpiresOn.String(),
		Created:   m.Created.String(),
		Updated:   m.Updated.String(),
		Body:      raw,
	}); err != nil {
		return fmt.Errorf("index: upsert memory: %w", err)
	}

	if err := qtx.DeleteTagsForMemory(ctx, m.ID); err != nil {
		return fmt.Errorf("index: clear tags: %w", err)
	}
	for _, tag := range dedupe(m.Tags) {
		if err := qtx.InsertTag(ctx, db.InsertTagParams{MemoryID: m.ID, Tag: tag}); err != nil {
			return fmt.Errorf("index: insert tag: %w", err)
		}
	}

	if err := qtx.DeleteLinksForMemory(ctx, m.ID); err != nil {
		return fmt.Errorf("index: clear links: %w", err)
	}
	for _, target := range dedupe(m.Links) {
		if err := qtx.InsertLink(ctx, db.InsertLinkParams{MemoryID: m.ID, TargetID: target}); err != nil {
			return fmt.Errorf("index: insert link: %w", err)
		}
	}

	if _, err := tx.ExecContext(ctx, `DELETE FROM memories_fts WHERE id = ?`, m.ID); err != nil {
		return fmt.Errorf("index: clear fts: %w", err)
	}
	if _, err := tx.ExecContext(ctx,
		`INSERT INTO memories_fts (id, title, body) VALUES (?, ?, ?)`,
		m.ID, m.Title, raw); err != nil {
		return fmt.Errorf("index: insert fts: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("index: commit: %w", err)
	}
	return nil
}

// Delete removes a memory and its tags, links, and full-text entry.
func (ix *Index) Delete(ctx context.Context, id string) error {
	tx, err := ix.sql.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("index: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	qtx := ix.q.WithTx(tx)

	if err := qtx.DeleteMemory(ctx, id); err != nil {
		return fmt.Errorf("index: delete memory: %w", err)
	}
	if err := qtx.DeleteTagsForMemory(ctx, id); err != nil {
		return fmt.Errorf("index: delete tags: %w", err)
	}
	if err := qtx.DeleteLinksForMemory(ctx, id); err != nil {
		return fmt.Errorf("index: delete links: %w", err)
	}
	if _, err := tx.ExecContext(ctx, `DELETE FROM memories_fts WHERE id = ?`, id); err != nil {
		return fmt.Errorf("index: delete fts: %w", err)
	}
	return tx.Commit()
}

// Path returns the vault-relative path stored for a memory id.
func (ix *Index) Path(ctx context.Context, id string) (string, error) {
	row, err := ix.q.GetMemory(ctx, id)
	if err != nil {
		return "", err
	}
	return row.Path, nil
}

// ListIDs returns every indexed memory id.
func (ix *Index) ListIDs(ctx context.Context) ([]string, error) {
	return ix.q.ListMemoryIDs(ctx)
}

// dedupe returns the input with empties removed and duplicates collapsed,
// preserving first-seen order.
func dedupe(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if s == "" {
			continue
		}
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}
