// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Link struct {
	MemoryID string
	TargetID string
}

type MemoriesFt struct {
	ID    string
	Title string
	Body  string
}

type Memory struct {
	ID         string
	Path       string
	Title      string
	Domain     string
	Project    string
	Source     string
	Lifecycle  string
	ExpiresOn  string
	Created    string
	Updated    string
	Importance int64
	Body       string
}

type Tag struct {
	MemoryID string
	Tag      string
}
