// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const deleteEmbeddingForMemory = `-- name: DeleteEmbeddingForMemory :exec
DELETE FROM memory_embeddings WHERE memory_id = ? AND provider = ? AND model = ?
`

type DeleteEmbeddingForMemoryParams struct {
	MemoryID string
	Provider string
	Model    string
}

func (q *Queries) DeleteEmbeddingForMemory(ctx context.Context, arg DeleteEmbeddingForMemoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteEmbeddingForMemory, arg.MemoryID, arg.Provider, arg.Model)
	return err
}

const deleteFTSForMemory = `-- name: DeleteFTSForMemory :exec
DELETE FROM memories_fts WHERE id = ?
`

func (q *Queries) DeleteFTSForMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFTSForMemory, id)
	return err
}

const deleteLinksForMemory = `-- name: DeleteLinksForMemory :exec
DELETE FROM links WHERE memory_id = ?
`

func (q *Queries) DeleteLinksForMemory(ctx context.Context, memoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteLinksForMemory, memoryID)
	return err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const deleteRelationshipsForMemory = `-- name: DeleteRelationshipsForMemory :exec
DELETE FROM memory_relationships WHERE source_id = ?
`

func (q *Queries) DeleteRelationshipsForMemory(ctx context.Context, sourceID string) error {
	_, err := q.db.ExecContext(ctx, deleteRelationshipsForMemory, sourceID)
	return err
}

const deleteRelationshipsTouchingMemory = `-- name: DeleteRelationshipsTouchingMemory :exec
DELETE FROM memory_relationships WHERE source_id = ? OR target_id = ?
`

type DeleteRelationshipsTouchingMemoryParams struct {
	SourceID string
	TargetID string
}

func (q *Queries) DeleteRelationshipsTouchingMemory(ctx context.Context, arg DeleteRelationshipsTouchingMemoryParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelationshipsTouchingMemory, arg.SourceID, arg.TargetID)
	return err
}

const deleteTagsForMemory = `-- name: DeleteTagsForMemory :exec
DELETE FROM tags WHERE memory_id = ?
`

func (q *Queries) DeleteTagsForMemory(ctx context.Context, memoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsForMemory, memoryID)
	return err
}

const getEmbeddingForMemory = `-- name: GetEmbeddingForMemory :one
SELECT memory_id, provider, model, dim, vector, content_hash, embedded_at
FROM memory_embeddings
WHERE memory_id = ? AND provider = ? AND model = ?
`

type GetEmbeddingForMemoryParams struct {
	MemoryID string
	Provider string
	Model    string
}

func (q *Queries) GetEmbeddingForMemory(ctx context.Context, arg GetEmbeddingForMemoryParams) (MemoryEmbedding, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddingForMemory, arg.MemoryID, arg.Provider, arg.Model)
	var i MemoryEmbedding
	err := row.Scan(
		&i.MemoryID,
		&i.Provider,
		&i.Model,
		&i.Dim,
		&i.Vector,
		&i.ContentHash,
		&i.EmbeddedAt,
	)
	return i, err
}

const getLinksForMemory = `-- name: GetLinksForMemory :many
SELECT target_id FROM links WHERE memory_id = ? ORDER BY target_id
`

func (q *Queries) GetLinksForMemory(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForMemory, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var target_id string
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemory = `-- name: GetMemory :one
SELECT id, path, title, domain, project, source, lifecycle, expires_on, created, updated, importance, body FROM memories WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.Domain,
		&i.Project,
		&i.Source,
		&i.Lifecycle,
		&i.ExpiresOn,
		&i.Created,
		&i.Updated,
		&i.Importance,
		&i.Body,
	)
	return i, err
}

const getRelationshipsForMemory = `-- name: GetRelationshipsForMemory :many
SELECT target_id, type, note FROM memory_relationships WHERE source_id = ? ORDER BY target_id, type
`

type GetRelationshipsForMemoryRow struct {
	TargetID string
	Type     string
	Note     string
}

func (q *Queries) GetRelationshipsForMemory(ctx context.Context, sourceID string) ([]GetRelationshipsForMemoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getRelationshipsForMemory, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRelationshipsForMemoryRow{}
	for rows.Next() {
		var i GetRelationshipsForMemoryRow
		if err := rows.Scan(&i.TargetID, &i.Type, &i.Note); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagsForMemory = `-- name: GetTagsForMemory :many
SELECT tag FROM tags WHERE memory_id = ? ORDER BY tag
`

func (q *Queries) GetTagsForMemory(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForMemory, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertFTSForMemory = `-- name: InsertFTSForMemory :exec
INSERT INTO memories_fts (id, title, body) VALUES (?, ?, ?)
`

type InsertFTSForMemoryParams struct {
	ID    string
	Title string
	Body  string
}

func (q *Queries) InsertFTSForMemory(ctx context.Context, arg InsertFTSForMemoryParams) error {
	_, err := q.db.ExecContext(ctx, insertFTSForMemory, arg.ID, arg.Title, arg.Body)
	return err
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO links (memory_id, target_id) VALUES (?, ?)
`

type InsertLinkParams struct {
	MemoryID string
	TargetID string
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink, arg.MemoryID, arg.TargetID)
	return err
}

const insertRelationship = `-- name: InsertRelationship :exec
INSERT INTO memory_relationships (source_id, target_id, type, note) VALUES (?, ?, ?, ?)
`

type InsertRelationshipParams struct {
	SourceID string
	TargetID string
	Type     string
	Note     string
}

func (q *Queries) InsertRelationship(ctx context.Context, arg InsertRelationshipParams) error {
	_, err := q.db.ExecContext(ctx, insertRelationship,
		arg.SourceID,
		arg.TargetID,
		arg.Type,
		arg.Note,
	)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (memory_id, tag) VALUES (?, ?)
`

type InsertTagParams struct {
	MemoryID string
	Tag      string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag, arg.MemoryID, arg.Tag)
	return err
}

const listEmbeddingsForModel = `-- name: ListEmbeddingsForModel :many
SELECT memory_id, provider, model, dim, vector, content_hash, embedded_at
FROM memory_embeddings
WHERE provider = ? AND model = ?
ORDER BY memory_id
`

type ListEmbeddingsForModelParams struct {
	Provider string
	Model    string
}

func (q *Queries) ListEmbeddingsForModel(ctx context.Context, arg ListEmbeddingsForModelParams) ([]MemoryEmbedding, error) {
	rows, err := q.db.QueryContext(ctx, listEmbeddingsForModel, arg.Provider, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryEmbedding{}
	for rows.Next() {
		var i MemoryEmbedding
		if err := rows.Scan(
			&i.MemoryID,
			&i.Provider,
			&i.Model,
			&i.Dim,
			&i.Vector,
			&i.ContentHash,
			&i.EmbeddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryIDs = `-- name: ListMemoryIDs :many
SELECT id FROM memories
`

func (q *Queries) ListMemoryIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO memory_embeddings (memory_id, provider, model, dim, vector, content_hash, embedded_at)
VALUES (?, ?, ?, ?, ?, ?, datetime('now'))
ON CONFLICT(memory_id, provider, model) DO UPDATE SET
    dim = excluded.dim,
    vector = excluded.vector,
    content_hash = excluded.content_hash,
    embedded_at = excluded.embedded_at
`

type UpsertEmbeddingParams struct {
	MemoryID    string
	Provider    string
	Model       string
	Dim         int64
	Vector      []byte
	ContentHash string
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.db.ExecContext(ctx, upsertEmbedding,
		arg.MemoryID,
		arg.Provider,
		arg.Model,
		arg.Dim,
		arg.Vector,
		arg.ContentHash,
	)
	return err
}

const upsertMemory = `-- name: UpsertMemory :exec

INSERT INTO memories (
    id, path, title, domain, project, source, lifecycle, expires_on, created, updated, importance, body
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    path       = excluded.path,
    title      = excluded.title,
    domain     = excluded.domain,
    project    = excluded.project,
    source     = excluded.source,
    lifecycle  = excluded.lifecycle,
    expires_on = excluded.expires_on,
    created    = excluded.created,
    updated    = excluded.updated,
    importance = excluded.importance,
    body       = excluded.body
`

type UpsertMemoryParams struct {
	ID         string
	Path       string
	Title      string
	Domain     string
	Project    string
	Source     string
	Lifecycle  string
	ExpiresOn  string
	Created    string
	Updated    string
	Importance int64
	Body       string
}

// query.sql holds static, type-safe queries sqlc generates Go for.
// Dynamic full-text search (combinable optional filters + FTS5 MATCH) is
// hand-written in search.go, which is why no search query appears here.
func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMemory,
		arg.ID,
		arg.Path,
		arg.Title,
		arg.Domain,
		arg.Project,
		arg.Source,
		arg.Lifecycle,
		arg.ExpiresOn,
		arg.Created,
		arg.Updated,
		arg.Importance,
		arg.Body,
	)
	return err
}
