// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const deleteLinksForMemory = `-- name: DeleteLinksForMemory :exec
DELETE FROM links WHERE memory_id = ?
`

func (q *Queries) DeleteLinksForMemory(ctx context.Context, memoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteLinksForMemory, memoryID)
	return err
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const deleteTagsForMemory = `-- name: DeleteTagsForMemory :exec
DELETE FROM tags WHERE memory_id = ?
`

func (q *Queries) DeleteTagsForMemory(ctx context.Context, memoryID string) error {
	_, err := q.db.ExecContext(ctx, deleteTagsForMemory, memoryID)
	return err
}

const getLinksForMemory = `-- name: GetLinksForMemory :many
SELECT target_id FROM links WHERE memory_id = ? ORDER BY target_id
`

func (q *Queries) GetLinksForMemory(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLinksForMemory, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var target_id string
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemory = `-- name: GetMemory :one
SELECT id, path, title, domain, project, source, lifecycle, expires_on, created, updated, body FROM memories WHERE id = ?
`

func (q *Queries) GetMemory(ctx context.Context, id string) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, id)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Title,
		&i.Domain,
		&i.Project,
		&i.Source,
		&i.Lifecycle,
		&i.ExpiresOn,
		&i.Created,
		&i.Updated,
		&i.Body,
	)
	return i, err
}

const getTagsForMemory = `-- name: GetTagsForMemory :many
SELECT tag FROM tags WHERE memory_id = ? ORDER BY tag
`

func (q *Queries) GetTagsForMemory(ctx context.Context, memoryID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsForMemory, memoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLink = `-- name: InsertLink :exec
INSERT INTO links (memory_id, target_id) VALUES (?, ?)
`

type InsertLinkParams struct {
	MemoryID string
	TargetID string
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertLink, arg.MemoryID, arg.TargetID)
	return err
}

const insertTag = `-- name: InsertTag :exec
INSERT INTO tags (memory_id, tag) VALUES (?, ?)
`

type InsertTagParams struct {
	MemoryID string
	Tag      string
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag, arg.MemoryID, arg.Tag)
	return err
}

const listMemoryIDs = `-- name: ListMemoryIDs :many
SELECT id FROM memories
`

func (q *Queries) ListMemoryIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listMemoryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemory = `-- name: UpsertMemory :exec

INSERT INTO memories (
    id, path, title, domain, project, source, lifecycle, expires_on, created, updated, body
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    path       = excluded.path,
    title      = excluded.title,
    domain     = excluded.domain,
    project    = excluded.project,
    source     = excluded.source,
    lifecycle  = excluded.lifecycle,
    expires_on = excluded.expires_on,
    created    = excluded.created,
    updated    = excluded.updated,
    body       = excluded.body
`

type UpsertMemoryParams struct {
	ID        string
	Path      string
	Title     string
	Domain    string
	Project   string
	Source    string
	Lifecycle string
	ExpiresOn string
	Created   string
	Updated   string
	Body      string
}

// query.sql holds the static, type-safe queries sqlc generates Go for.
// Dynamic full-text search (combinable optional filters + FTS5) is hand-written
// in search.go, which is why no search query appears here.
func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMemory,
		arg.ID,
		arg.Path,
		arg.Title,
		arg.Domain,
		arg.Project,
		arg.Source,
		arg.Lifecycle,
		arg.ExpiresOn,
		arg.Created,
		arg.Updated,
		arg.Body,
	)
	return err
}
